/* This data is autogenerated. Do not modify. */
module.exports = {
  campaigns: [
    {
      id: '001',
      title: 'Tiësto\'s Barcelona Weekender',
    },
    {
      id: '002',
      title: 'Peggy Gou x Miami',
    },
  ],
  products: [
    {
      id: '001',
      campaign_id: '001',
      title: 'Party Pass Only',
      price: 75.0,
    },
    {
      id: '002',
      campaign_id: '001',
      title: 'Deluxe Room + Party Pass',
      price: 275.0,
    },
    {
      id: '003',
      campaign_id: '001',
      title: 'Family Room Beach Side + Party Pass',
      price: 300.0,
    },
    {
      id: '004',
      campaign_id: '001',
      title: 'Suite Beach Side + Party Pass',
      price: 350.0,
    },
    {
      id: '005',
      campaign_id: '001',
      title: 'Junior Suite + Party Pass',
      price: 375.0,
    },
    {
      id: '006',
      campaign_id: '002',
      title: 'Grand Suite + Party Pass',
      price: 475.0,
    },
    {
      id: '007',
      campaign_id: '002',
      title: 'Deluxe Suite + Party Pass',
      price: 500.0,
    },
  ],
  rewards: [
    {
      id: '001',
      campaign_id: '001',
      name: 'Tiësto\'s Barcelona Weekender Flag',
      description:
        'Stand out in a crowd with this limited edition Tiësto\'s Barcelona Weekender flag',
      image:
        'https://d3mivsidb2c4zk.cloudfront.net/client/reward_images/1519118356.png',
      position: 0,
      points: 500,
      quantity: 100,
      status: 'on-sale',
      publishedAt: '2018-02-19T11:28:17.861872+00:00',
      capPerReviewifyMember: 1,
    },
    {
      id: '002',
      campaign_id: '001',
      name: 'Free Drink Voucher',
      description: 'Get a free drink on us!',
      image:
        'https://d3mivsidb2c4zk.cloudfront.net/client/reward_images/1519128358.jpg',
      position: 1,
      points: 1000,
      quantity: 0,
      status: 'on-sale',
      publishedAt: '2018-02-19T11:28:42.830133+00:00',
      capPerReviewifyMember: 5,
    },
    {
      id: '003',
      campaign_id: '001',
      name: 'Stay on a yacht',
      description:
        'Our best seller will be rewarded by staying at a yacht during their time at Tiësto\'s Barcelona Weekender.',
      image:
        'https://d3mivsidb2c4zk.cloudfront.net/client/reward_images/1519129609.jpg',
      position: 2,
      points: 10000,
      quantity: 1,
      status: 'on-sale',
      publishedAt: '2018-02-19T11:29:32.807821+00:00',
      capPerReviewifyMember: 1,
    },
    {
      id: '004',
      campaign_id: '001',
      name: 'Free Hotdog',
      description: "We'll feed you!",
      image:
        'https://d3mivsidb2c4zk.cloudfront.net/client/reward_images/1519138501.png',
      position: 3,
      points: 100,
      quantity: 0,
      status: 'on-sale',
      publishedAt: '2018-02-19T11:30:50.780785+00:00',
      capPerReviewifyMember: 5,
    },
    {
      id: '005',
      campaign_id: '001',
      name: 'Meet and Greet with Tiësto',
      description:
        "Meet the world famous Tiësto. You'll get to chat to him backstage before he goes on to play the Tiësto\'s Barcelona Weekender closing set.",
      image:
        'https://d3mivsidb2c4zk.cloudfront.net/client/reward_images/1519137243.jpg',
      position: 4,
      points: 5000,
      quantity: 3,
      status: 'on-sale',
      publishedAt: '2018-02-19T11:32:29.551609+00:00',
      capPerReviewifyMember: 1,
    },
    {
      id: '006',
      campaign_id: '002',
      name: 'Peggy Gou x Miami Flag',
      description:
        'Stand out in a crowd with this limited edition Peggy Gou x Miami festival flag',
      image:
        'https://d3mivsidb2c4zk.cloudfront.net/client/reward_images/1519087546.jpg',
      position: 5,
      points: 3000,
      quantity: 3,
      status: 'on-sale',
      publishedAt: '2018-02-19T11:32:46.309106+00:00',
      capPerReviewifyMember: 1,
    },
    {
      id: '007',
      campaign_id: '001',
      name: 'Personal DJ Set',
      description:
        "You'll get to personally open one of our smaller tents on Thursday night with your own DJ set.",
      image:
        'https://d3mivsidb2c4zk.cloudfront.net/client/reward_images/1519087546.jpg',
      position: 5,
      points: 3000,
      quantity: 3,
      status: 'on-sale',
      publishedAt: '2018-02-19T11:32:46.309106+00:00',
      capPerReviewifyMember: 1,
    },
  ],
};
